matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: python
      python: 3.6
      sudo: required
      addons:
         homebrew:
           update: true
           taps: zhaofeng-shu33/liblemonformula
           packages:
             - gsl
             - glib-static
    - os: osx
      osx_image: xcode10.3
      language: python
      python: 3.7
      sudo: required
      addons:
        homebrew:
          taps: zhaofeng-shu33/liblemonformula
          packages:
            - gsl
            - glib-static
install:
  - python -m pip install cython twine

script:
  - export STATIC_GSL=1 && python3 setup.py bdist_wheel
  - python -m twine upload dist/* -u zhaofeng-shu33 && echo "success" || echo "failed"

